# -*- mode: ruby -*-
# vi: set ft=ruby :

consul_servers = {
  :consul1 => '192.168.210.101',
  :consul2 => '192.168.210.102'
}
consul_servers2 = {
  :consul3 => '192.168.210.103'
}
consul_ui_servers = {
  :consul4 => '192.168.210.104'
}

Vagrant.configure("2") do |config|
  config.vm.box = "sloth-centos-7-1.0.0"
  config.vm.box_check_update = false

  config.ssh.keys_only = false
  config.ssh.username = "sloth"
  config.ssh.password = "sloth@linux"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.gui = false
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end

  # 配置host
  consul_servers.each do |server_name, server_ip|
    config.vm.provision "shell", inline: <<-SHELL
      echo '\n#{server_ip} #{server_name}' | sudo tee -a /etc/hosts
    SHELL
  end
  consul_ui_servers.each do |server_name, server_ip|
    config.vm.provision "shell", inline: <<-SHELL
      echo '\n#{server_ip} #{server_name}' | sudo tee -a /etc/hosts
    SHELL
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo /sbin/iptables -I INPUT -p tcp --dport 8300 -j ACCEPT
    sudo /sbin/iptables -I INPUT -p tcp --dport 8301 -j ACCEPT
    sudo /sbin/iptables -I INPUT -p tcp --dport 8302 -j ACCEPT
    sudo /sbin/iptables -I INPUT -p tcp --dport 8300 -j ACCEPT
    sudo /sbin/iptables -I INPUT -p tcp --dport 8500 -j ACCEPT
    sudo /sbin/iptables -I INPUT -p tcp --dport 8600 -j ACCEPT
    sudo service iptables save
    sudo systemctl restart iptables.service
    unzip /vagrant/support/consul_0.8.2_linux_amd64.zip -d /opt/sloth/consul
  SHELL

  # 配置虚拟机
  consul_servers.each do |server_name, server_ip|
    config.vm.define server_name do |server_config|
      server_config.vm.network "private_network", ip: server_ip
      server_config.vm.provision "shell", inline: <<-SHELL
        # 启动
        nohup /opt/sloth/consul/consul agent -server -bootstrap-expect=3 -data-dir=/tmp/consul -node=#{server_name} -bind=#{server_ip} -dc=dc1 > /vagrant/#{server_name}.log 2>&1 &
      SHELL
    end
  end
  consul_ui_servers.each do |server_name, server_ip|
    config.vm.define server_name do |server_config|
      server_config.vm.network "private_network", ip: server_ip
      server_config.vm.provision "shell", inline: <<-SHELL
        # 启动
        nohup /opt/sloth/consul/consul agent -data-dir=/tmp/consul -node=#{server_name} -bind=#{server_ip} -dc=dc1 -ui -client #{server_ip}  > /vagrant/#{server_name}.log 2>&1 &
      SHELL
    end
  end
  consul_servers2.each do |server_name, server_ip|
    config.vm.define server_name do |server_config|
      server_config.vm.network "private_network", ip: server_ip
      server_config.vm.provision "shell", inline: <<-SHELL
        # 启动
        nohup /opt/sloth/consul/consul agent -server -bootstrap-expect=3 -data-dir=/tmp/consul -node=#{server_name} -bind=#{server_ip} -dc=dc1 > /vagrant/#{server_name}.log 2>&1 &
        /opt/sloth/consul/consul join 192.168.210.101
        /opt/sloth/consul/consul join 192.168.210.102
        /opt/sloth/consul/consul join 192.168.210.104
      SHELL
    end
  end
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
end
